# Generated by Django 3.2 on 2022-04-06 12:43

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_avatar'),
        ('post', '0002_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='userprofile.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'gif', 'svg'])], verbose_name='image'),
        ),
    ]
