# Generated by Django 3.2 on 2022-04-03 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='blank-avatar_pxjsla.png', max_length=255, verbose_name='image'),
        ),
    ]
